export const PERMISSIONS = {
    INVITE_USER: "INVITE_USER",
    CREATE_CHANNEL: "CREATE_CHANNEL",
    SEND_MESSAGE: "SEND_MESSAGE",
    APPROVE_LEAVE: "APPROVE_LEAVE",
    VIEW_ANALYTICS: "VIEW_ANALYTICS",
};