import { PERMISSIONS } from "./permissions.js";

export const ROLE_PERMISSIONS = {
    ADMIN: [
        PERMISSIONS.INVITE_USER,
        PERMISSIONS.CREATE_CHANNEL,
        PERMISSIONS.SEND_MESSAGE,
        PERMISSIONS.APPROVE_LEAVE,
        PERMISSIONS.VIEW_ANALYTICS,
    ],

    MANAGER: [
        PERMISSIONS.CREATE_CHANNEL,
        PERMISSIONS.SEND_MESSAGE,
        PERMISSIONS.APPROVE_LEAVE,
    ],

    EMPLOYEE: [
        PERMISSIONS.SEND_MESSAGE,
    ],
};